[workspace]
resolver = "3"

members = [
    "crates/runenui_core",
    "crates/runenui_text",
    "crates/runenui_runtime",
    "crates/runenui_render_wgpu",
    "crates/runenui_winit",
    "crates/runenui_testing",

    "examples/counter",
    "examples/reference_winit",

    "tests/external_widget",
    "tests/external_renderer",
    "tests/external_host",

    "xtask",
]

[workspace.package]
version = "0.1.0"
repository = "https://github.com/dornglut/runen-ui"
license = "GPL-3.0-only"
publish = false
edition = "2024"
rust-version = "1.93.0"

[workspace.dependencies]

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
