name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: RunenUI validation
    uses: dornglut/github-workflows/.github/workflows/reusable-rust-cargo-validate.yml@8df7328bb0c3997f2562e7498e97124e3be94d73
